- package-lock.json
- src/controllers/notarization.controller.js
- src/docs/swaggerDef.js
- src/routes/v1/notarization.route.js
- src/services/notarization.service.js
- yarn.lock
- Added Swagger spec for status tracking endpoints
- Refactored swaggerDef.js to include Notarizations schema and standardized responses
- Improved error handling in getDocumentStatus function using destructuring
- Refined file upload and status tracking logic for better API consistency
> feat(statusTracking): Add status tracking feature and improve error handling

- src/config/roles.js
- src/controllers/admin.controller.js
- src/docs/components.yml
- src/models/payment.model.js
- src/routes/v1/admin.route.js
- src/routes/v1/payment.route.js
- src/services/admin.service.js
- src/services/notarization.service.js
- yarn.lock
This pull request includes changes to add new payment-related features and clean up the documentation. The most important changes include adding new roles and endpoints for retrieving payment totals by service, updating the payment model to include references to related documents and services, and cleaning up the `components.yml` file by removing unnecessary lines.
* [`src/config/roles.js`](diffhunk://#diff-7c0e7c53fa672d2c5e51fc023713e6abd5704d92e39f54c0e22906c8e22f6e05R44-R46): Added roles for `getPaymentTotalByService`, `approveSignatureByUser`, and `approveSignatureBySecretary`.
* [`src/controllers/admin.controller.js`](diffhunk://#diff-056aaff6f16777d5fe3aae04d5039611a46ed72790ab9697824e53e938511aabR62-R67): Added `getPaymentTotalByService` method to retrieve payment totals by …
> Refactor code and add new endpoint for calculating payment total by service in admin controller

- src/routes/v1/notarization.route.js
- src/validations/notarization.validation.js
This pull request includes changes to improve logging and validation in the notarization service. The most important changes are the addition of a console log for uploaded files and an update to the validation schema for requester information.
Logging improvements:
* [`src/routes/v1/notarization.route.js`](diffhunk://#diff-8f9d8bd5e5621ea11bed10370ff77d638ef146cea4333577005bf7829e63b659R70): Added a console log to display uploaded files for better debugging.
Validation schema updates:
* [`src/validations/notarization.validation.js`](diffhunk://#diff-7c5b41ec5b6dda0df4ade8d1f7e052e30e43baa6a6d1b5dfdb205fcc6c46c9beR25): Added a new `fullName` field to the `requesterInfo` validation schema.
> Refactor file upload and validation code

- src/controllers/admin.controller.js
- src/routes/v1/admin.route.js
- src/services/admin.service.js
This pull request involves changes across multiple files to standardize the period parameters used in various functions and API routes. The most important changes include updating the allowed period values and modifying the corresponding service functions to handle these new values.
* [`src/controllers/admin.controller.js`](diffhunk://#diff-056aaff6f16777d5fe3aae04d5039611a46ed72790ab9697824e53e938511aabL7-R7): Updated the allowed period values to 'today', 'current_week', 'current_month', and 'current_year' in various functions (`getDocumentCount`, `getUserCount`, `getDocumentsByNotaryField`, `getSessionCount`, `getPaymentTotalByNotarizationField`). [[1]](diffhunk://#diff-056aaff6f16777d5fe3aae04d5039611a46ed72790ab9697824e53e938511aabL7-R7) …
> feat: update allowed periods in admin controller and routes for document and user count retrieval

- src/controllers/admin.controller.js
- src/models/approveHistory.model.js
- src/services/cron.service.js
- src/services/notarization.service.js
This pull request includes several updates to the `admin.controller`, `approveHistory.model`, `cron.service`, and `notarization.service` files. The changes mainly focus on adding a new auto-forwarding feature for document status and adjusting the schema requirements.
* Added `autoForwardPendingToVerification` function to automatically move documents from 'pending' to 'verification' status if they have been in 'pending' for more than a minute (`src/services/notarization.service.js`).
* Scheduled the `autoForwardPendingToVerification` job to run every minute in the cron job service (`src/services/cron.service.js`).
* Made the `userId` field in the `ApproveHistorySchema` optional (`src/models/approveHistory.model.js`).
* Removed a redundant comment in the `admin.controller` export statement …
> feat: implement auto-forwarding of pending documents to verification status and update ApproveHistory model

- src/controllers/user.controller.js
- src/models/document.model.js
- src/models/plugins/toJSON.plugin.js
- src/models/user.model.js
- src/services/user.service.js
- src/validations/user.validation.js
This pull request includes several updates to the user and document models, as well as enhancements to the user-related services and validations. The key changes involve adding a status field to the user model, modifying the document model to include timestamps, and updating the user controller and service to handle document counts.
* **User Model**: Added a `status` field with possible values 'active', 'inactive', 'suspended', and 'deleted' (`src/models/user.model.js`).
* **Document Model**: Updated to include timestamps for `createdAt` and `updatedAt` fields (`src/models/document.model.js`).
* **User Service**: Modified the `queryUsers` function to include document counts for each user (`src/services/user.service.js`).
* **User Controller**: Updated the `getUser` function to include the …
> Enhance user and document models; add document count to user responses

- src/controllers/email.controller.js
- src/controllers/index.js
- src/controllers/notarization.controller.js
- src/models/statusTracking.model.js
- src/public/templates/document_status_update.html
- src/public/templates/document_upload_confirmation.html
- src/public/templates/email.html
- src/public/templates/invitation_email.html
- src/public/templates/payment_email.html
- src/public/templates/reset_password.html
- src/public/templates/verification_email.html
- src/routes/v1/email.route.js
- src/routes/v1/index.js
- src/services/email.service.js
- src/services/notarization.service.js
- src/services/session.service.js
- src/validations/notarization.validation.js
This pull request introduces a new email controller and corresponding email templates. It also refactors the existing code to use the new email controller for sending various types of emails. The most important changes include adding new controller methods for sending different types of emails, integrating the new email controller into the main application, and creating new HTML templates for the emails.
* [`src/controllers/email.controller.js`](diffhunk://#diff-4712e6bd72d5e92c17d94344a3c106d6d629d2301f391aae05927689954a4978R1-R78): Added new controller methods for sending reset password, verification, invitation, document status update, payment, and document upload confirmation emails.
* [`src/controllers/index.js`](diffhunk://#diff-4d200a6251dc3698ded70e8f6f9580e2d552ec30b63d167c135dac3 …
> refactor: update feedback field name and enhance email notification logic; add new email templates

- src/controllers/admin.controller.js
- src/services/admin.service.js
This pull request includes changes to the `getEmployeeList` function in both the `admin.controller.js` and `admin.service.js` files to improve code clarity and functionality.
Changes to improve code clarity:
* [`src/controllers/admin.controller.js`](diffhunk://#diff-056aaff6f16777d5fe3aae04d5039611a46ed72790ab9697824e53e938511aabL96-R96): Commented out a debug `console.log` statement to clean up the code.
Changes to improve functionality:
* [`src/services/admin.service.js`](diffhunk://#diff-80beb6ef668ca00e266e95a002f1d3d7e97bef2a463b64e57530970b026749ffL275-R275): Removed the `.select('name email role')` method call to return all fields of the employee list instead of only the `name`, `email`, and `role` fields.
> refactor: remove console log from getEmployeeList and clean up query selection

- src/docs/components.yml
- src/models/user.model.js
- src/routes/v1/user.route.js
- src/services/user.service.js
- src/validations/user.validation.js
This pull request introduces new fields to the user model and updates related components to accommodate these changes. The main additions are `citizenId`, `phoneNumber`, and `address` fields, which include further subdivisions for `province`, `district`, `town`, and `street`.
* Added new fields `citizenId`, `phoneNumber`, and `address` with its properties (`province`, `district`, `town`, `street`) to the user schema in `src/models/user.model.js`.
* Updated `src/docs/components.yml` to include examples and definitions for the new fields `citizenId`, `phoneNumber`, and `address`.
* Updated `src/routes/v1/user.route.js` to document the new fields in the user object.
* Modified `src/validations/user.validation.js` to validate the new fields.
* Updated `src/services/user.service.js` to include …
> Update user info

- src/services/cron.service.js
- src/services/email.service.js
- src/services/index.js
- src/services/session.service.js
This pull request includes several changes to the cron job scheduling and session status auto-forwarding functionality. The most important changes involve adding a new cron job to auto-forward session statuses and updating the session service to handle this new functionality.
* [`src/services/cron.service.js`](diffhunk://#diff-ecef8c6451b4d6d72f88c73c79ac932cc428d2a6027b4db0f6c8c93328d5b102R4): Added a new import for `autoForwardSessionStatus` from `session.service` and scheduled it to run every minute. [[1]](diffhunk://#diff-ecef8c6451b4d6d72f88c73c79ac932cc428d2a6027b4db0f6c8c93328d5b102R4) [[2]](diffhunk://#diff-ecef8c6451b4d6d72f88c73c79ac932cc428d2a6027b4db0f6c8c93328d5b102L27-R30)
* [`src/services/session.service.js`](diffhunk://#diff-d07c2ab187d45f994e05063bdd098f7734559a10bccefbb22 …
> Refactor cron service to include auto-forwarding session status

- src/public/templates/document_upload_confirmation.html
- src/public/templates/invitation_email.html
- src/public/templates/payment_email.html
- src/public/templates/reset_password.html
- src/public/templates/verification_email.html
- src/services/email.service.js
…This pull request includes several changes to improve the usability and consistency of email templates, as well as a minor update in the email service. The most important changes include adding `target="_blank"` to links in email templates, removing unnecessary HTML comments, and updating the title and styles in the password reset email template.
Improvements to email templates:
* [`src/public/templates/document_upload_confirmation.html`](diffhunk://#diff-02ff8a501078ebe424c0c04cccef7124f65f64329a0584c2fe49f8af2d9c2693L78-L82): Added `target="_blank"` to the "View Document Status" link and removed HTML comments. [[1]](diffhunk://#diff-02ff8a501078ebe424c0c04cccef7124f65f64329a0584c2fe49f8af2d9c2693L78-L82) [[2]](diffhunk://#diff-02ff8a501078ebe424c0c04cccef7124f65f64329a0584c2fe49f8af2d9c …
> Add target="_blank" to links in email templates and update reset password email structure

- src/docs/components.yml
- src/models/document.model.js
- src/models/notarizationField.model.js
- src/models/notarizationService.model.js
- src/routes/v1/notarization.route.js
- src/services/notarization.service.js
- src/validations/notarization.validation.js
This pull request includes several changes to enhance the schema definitions, validation, and processing of notarization-related data. The most important changes involve adding new fields to the schemas, updating validation rules, and ensuring proper data handling in the routes and services.
Schema enhancements:
* [`src/docs/components.yml`](diffhunk://#diff-848be3bdb1e3a2866f0025a7a1348c31f1d74cd2c521c7f99d5b71a9eac90f7aR106-R108): Added `amount`, `name_en`, `code`, and `required_documents` fields to various components. [[1]](diffhunk://#diff-848be3bdb1e3a2866f0025a7a1348c31f1d74cd2c521c7f99d5b71a9eac90f7aR106-R108) [[2]](diffhunk://#diff-848be3bdb1e3a2866f0025a7a1348c31f1d74cd2c521c7f99d5b71a9eac90f7aR203-R208) [[3]](diffhunk://#diff-848be3bdb1e3a2866f0025a7a1348c31f1d74cd2c521c7f99d5b71 …
> Add required fields and validations for notarization documents and services

- src/config/payos.js
- src/controllers/payment.controller.js
- src/routes/v1/payment.route.js
- src/services/payment.service.js
This pull request introduces several new features and improvements to the payment module, including new endpoints for retrieving and updating payment statuses and refactoring the integration with the PayOS API. The most important changes are summarized below:
* Added `getPaymentStatus` and `updateAllPayments` functions to the `payment.controller.js` to handle new endpoints for retrieving a single payment status and updating all payments, respectively.
* Updated `payment.route.js` to include new routes for `getPaymentStatus` and `updateAllPayments` endpoints.
* Added Swagger documentation for the new `get-payment-status` and `update-all-payments` endpoints.
* Refactored the PayOS API integration in `payment.service.js` to use a single instance of `payOS` from the configuration file. …
> Add payment status retrieval and update functionality

- src/services/payment.service.js
This pull request includes a refactoring of the `payment.service.js` file to improve the organization and readability of the code. The main change involves moving the `getPaymentStatus` function to a different location within the file.
Code organization improvements:
* [`src/services/payment.service.js`](diffhunk://#diff-1dbdab5179cca2de6a762d8a5c595f5e493764452956d7fc762653b5e0fd8269R86-R115): Moved the `getPaymentStatus` function to a new position above the `updateAllPayments` function to improve code structure. [[1]](diffhunk://#diff-1dbdab5179cca2de6a762d8a5c595f5e493764452956d7fc762653b5e0fd8269R86-R115) [[2]](diffhunk://#diff-1dbdab5179cca2de6a762d8a5c595f5e493764452956d7fc762653b5e0fd8269L131-L160)
> Refactor getPaymentStatus function to improve error handling and maintainability

- finetune-model/fine_tune_prompts.ipynb
- finetune-model/fine_tune_prompts.txt
- finetune-model/notarization_service_dataset.csv
- src/services/chatbot.service.js
This pull request includes significant updates to the `finetune-model` project, specifically focusing on the `fine_tune_prompts.ipynb` notebook and the `fine_tune_prompts.txt` file. The changes introduce new functionality to create fine-tune prompts from a CSV file and provide detailed examples of notarization services.
Notebook and script enhancements:
* [`finetune-model/fine_tune_prompts.ipynb`](diffhunk://#diff-ec046e674c37331480b8f99d1f9f6ef178f3803e31233530a46af8b351f6a397R1-R193): Added new code cells to install necessary packages, read data from a CSV file, and generate fine-tune prompts. The notebook now includes a function to create fine-tune prompts from a dataset and save them to a text file.
New fine-tune prompt examples:
* …
> Update chatbot service model and enhance generation configuration; add fine-tune prompt creation notebook

- src/public/cancel.html
- src/public/index.html
- src/public/style.css
- src/public/success.html
- src/public/templates/document_upload_confirmation.html
- src/public/templates/invitation_email.html
- src/public/templates/payment_email.html
- src/public/templates/reset_password.html
- src/public/templates/verification_email.html
- src/services/email.service.js
This pull request includes significant updates to the HTML files for better styling and content, as well as minor CSS and email template adjustments. The most important changes are the redesign of the `index.html` file, the addition of `!important` to button text color in multiple email templates, and an update to the reset password URL in the email service.
HTML and styling updates:
* [`src/public/index.html`](diffhunk://#diff-7ea7e6556d44139dd339a52fea90d3d1130b3ef84c0c03fc40fe238c448f6c92R3-R138): Redesigned the page with new fonts, styles, and content, including a new API message and repository cards.
* [`src/public/cancel.html`](diffhunk://#diff-26b8b064456654b51cb92efa555a81cfa6b45d56e9dfdc5b46efcf3ace2c3ef3R3-R20): Removed the "return to payment link creation" button.
* …
> Refactor HTML templates for consistency and improve styling; update email service to use dynamic client URL for password reset

- src/config/roles.js
- src/controllers/index.js
- src/controllers/userWallet.controller.js
- src/docs/components.yml
- src/routes/v1/index.js
- src/routes/v1/userWallet.route.js
- src/services/email.service.js
- src/services/notarization.service.js
- src/services/userWallet.service.js
This pull request introduces a new feature for managing user wallets and NFTs, along with several enhancements and bug fixes in different parts of the codebase. The most important changes include adding new routes and controllers for user wallet operations, updating services to handle NFT transfers, and improving error handling in the notarization process.
* [`src/controllers/userWallet.controller.js`](diffhunk://#diff-f18a3602359b471ebf224bec4d09262756d5a9198edad6a9ebcba7242793ae54R18-R47): Added new methods `getWallet` and `transferNFT` to handle fetching user wallets and transferring NFTs between users.
* [`src/routes/v1/userWallet.route.js`](diffhunk://#diff-8ef04b018f95e6a995c18831890ea1f3a917d0f1895e838b6165e36732094598R1-R111): Created new routes for user wallet operations, …
> Add user wallet functionality: implement getWallet and transferNFT methods, update routes and roles

- src/controllers/userWallet.controller.js
- src/routes/v1/userWallet.route.js
- src/services/userWallet.service.js
This pull request includes significant changes to the `userWallet` feature, primarily focusing on updating the transfer process to use the recipient's email instead of their user ID. The most important changes include updates to the controller, routes, and service files to reflect this new approach.
Updates to transfer process:
* [`src/controllers/userWallet.controller.js`](diffhunk://#diff-f18a3602359b471ebf224bec4d09262756d5a9198edad6a9ebcba7242793ae54L37-R39): Modified the `transferNFT` function to accept `toUserEmail` instead of `toUserId` and updated the call to `userWalletService.transferNFT` accordingly.
* [`src/services/userWallet.service.js`](diffhunk://#diff-2e06c8b0fb2ba0a26cc5f2cc4b29e22eb38b30c373e9c6ef688b9a6a630ee7d0L82-R82): Updated the `transferNFT` function to find the …
> Refactor NFT transfer to use recipient email instead of user ID and update API documentation

- src/controllers/session.controller.js
- src/docs/components.yml
- src/models/requestSessionSignature.model.js
- src/routes/v1/session.route.js
- src/services/session.service.js
- src/validations/session.validation.js
This pull request includes several changes to the session management functionality, including enhancements to the approval process, file handling, and schema updates. The most important changes are summarized below:
* Modified the `approveSignatureSessionByUser` function to include user ID and handle signature images more robustly. [[1]](diffhunk://#diff-3310842cd66613cef0f6a81dfe8c78aa66e7245076af5c8c159aa5a706e0f0abL140-R142) [[2]](diffhunk://#diff-d07c2ab187d45f994e05063bdd098f7734559a10bccefbb22a069db7c5a6f9b0L865-R953)
* Updated the `approveSignatureSessionByNotary` function to ensure all users and the creator have signed before approval.
* Added a new endpoint to delete files from a session (`deleteFile` function), including validation and routing. …
> Add delete file functionality and update session model to include user emails

- src/controllers/notarization.controller.js
- src/controllers/session.controller.js
- src/middlewares/parseJson.js
- src/models/session.model.js
- src/routes/v1/notarization.route.js
- src/routes/v1/session.route.js
- src/services/email.service.js
- src/services/notarization.service.js
- src/services/session.service.js
- src/services/userWallet.service.js
- src/validations/notarization.validation.js
- src/validations/session.validation.js
This pull request includes several changes to the notarization and session management functionalities in the codebase. The most important changes include the addition of new parameters for file handling, improvements to JSON parsing middleware, and updates to the session and document creation processes.
* [`src/controllers/notarization.controller.js`](diffhunk://#diff-e0b1f720ebbfb63e320fdd6167ac55233175719d3e8487f857df8c9ca5d4e1c6L18-R24): Added new parameters `fileIds` and `customFileNames` to the `createDocument` function to handle additional file information.
* [`src/services/notarization.service.js`](diffhunk://#diff-4599cbb117c8f9141bf941f94d5152e00dc0381ea261f9c3cd1db8f596d2e3d1L34-R36): Updated the `createDocument` function to handle files from the user's wallet and process file …
> Refactor notarization workflow to support optional file attributes and update email invitation URL

- package-lock.json
- package.json
- src/config/roles.js
- src/controllers/admin.controller.js
- src/controllers/userWallet.controller.js
- src/public/templates/nft_payment_email.html
- src/routes/v1/admin.route.js
- src/routes/v1/session.route.js
- src/routes/v1/userWallet.route.js
- src/services/admin.service.js
- src/services/email.service.js
- src/services/payment.service.js
- src/services/userWallet.service.js
- yarn.lock
This pull request introduces new features and enhancements, primarily focusing on exporting metrics data to an Excel file and adding functionality for purchasing documents. The most important changes are listed below:
* Added functionality to export metrics data to an Excel file for specified periods (`today`, `current_week`, `current_month`, `current_year`). This includes updates to the `admin.controller.js`, `admin.route.js`, and `admin.service.js` files. [[1]](diffhunk://#diff-056aaff6f16777d5fe3aae04d5039611a46ed72790ab9697824e53e938511aabR134-R147) [[2]](diffhunk://#diff-e72bd8d0b3cb8037c3896a9628c71ddfc4e1e34f5d85f400e77f045a2259b896R35-R37) [[3]](diffhunk://#diff-80beb6ef668ca00e266e95a002f1d3d7e97bef2a463b64e57530970b026749ffR5-R6)
* Added the ability for users to purchase …
> Add document purchase and metrics export functionality; update roles and email template for NFT payments
